### ISSUE TITLE
Issues importing a CD into the library. Segfault when changing codec.

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1134]
When I try to import the tracks of a CD in my library and choose a codec (FLAC), cantata crashes with a segfault the same moment that I click on the codec.

```
(gdb) run
Starting program: /usr/bin/cantata 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe6493700 (LWP 30958)]
[New Thread 0x7fffd9550700 (LWP 30959)]
Icon theme "cantata" not found.
[New Thread 0x7fffcd2fe700 (LWP 30960)]
[New Thread 0x7fffccafd700 (LWP 30961)]
[New Thread 0x7fffc7125700 (LWP 30962)]
[New Thread 0x7fffc6924700 (LWP 30963)]
MEDIA CHANGED in "/org/freedesktop/UDisks2/block_devices/sr0" ; size is: 575123456
[New Thread 0x7fffc5110700 (LWP 31136)]
[New Thread 0x7fffb3fff700 (LWP 31141)]
[New Thread 0x7fffb37fe700 (LWP 31142)]
[New Thread 0x7fffb2db8700 (LWP 31143)]
[Thread 0x7fffccafd700 (LWP 30961) exited]

Thread 1 "cantata" received signal SIGSEGV, Segmentation fault.
0x00007ffff5160d80 in QComboBox::currentIndex() const () from /usr/lib/libQt5Widgets.so.5
(gdb) backtrace
#0  0x00007ffff5160d80 in QComboBox::currentIndex() const () from /usr/lib/libQt5Widgets.so.5 
#1  0x0000555555a24bb4 in DevicePropertiesWidget::settings() ()                               
#2  0x0000555555a251c2 in DevicePropertiesWidget::checkSaveable() ()                          
#3  0x00007ffff4368126 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#4  0x0000555555aa21af in ValueSlider::valueChanged(int) ()                                     
#5  0x0000555555a38762 in ValueSlider::onSliderChanged(int) ()                                  
#6  0x0000555555a38d64 in ValueSlider::setValues(Encoders::Encoder const&) ()                   
#7  0x0000555555a25a65 in DevicePropertiesWidget::transcoderChanged() ()                        
#8  0x00007ffff4368126 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff515e8b2 in QComboBox::currentIndexChanged(int) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff5160884 in ?? () from /usr/lib/libQt5Widgets.so.5                                          
#11 0x00007ffff5161e71 in ?? () from /usr/lib/libQt5Widgets.so.5                                          
#12 0x00007ffff5162012 in ?? () from /usr/lib/libQt5Widgets.so.5                                          
#13 0x00007ffff5167d8d in ?? () from /usr/lib/libQt5Widgets.so.5                                          
#14 0x00007ffff4368126 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff515ef6f in ?? () from /usr/lib/libQt5Widgets.so.5                                          
#16 0x00007ffff433823c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff5055f38 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff505dfb1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5     
#19 0x00007ffff4338570 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff505cf3a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5                                                                                    
#21 0x00007ffff50b0b92 in ?? () from /usr/lib/libQt5Widgets.so.5                                                       
#22 0x00007ffff50b35a1 in ?? () from /usr/lib/libQt5Widgets.so.5                                                       
#23 0x00007ffff5055f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5    
#24 0x00007ffff505da36 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5                  
#25 0x00007ffff4338570 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5        
#26 0x00007ffff48973d4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#27 0x00007ffff4898f36 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5                                                                                            
#28 0x00007ffff487048c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#29 0x00007fffe90666b1 in ?? () from /usr/lib/libQt5XcbQpa.so.5                                                                                             
#30 0x00007fffefbf3270 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#31 0x00007fffefbf4f69 in ?? () from /usr/lib/libglib-2.0.so.0
#32 0x00007fffefbf4fae in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff43931e1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#34 0x00007ffff433699b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff433f9e8 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#36 0x00005555556dcfcd in main ()
```

**Comment by CDrummond** [comment]
This should now be fixed. Can you please update and confirm?

**Comment by Tichy** [comment]
I confirm that is fixed. Thanks.
