### ISSUE TITLE
Segfault 

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#1244]
The commit 5d89f1a9ca2a5923ba801ac014edcdf7a5fc81c5 introduce a segfault on my machine.
I'm willing to help you to find it.

```
$ ./cantata
qt5ct: using qt5ct plugin
Erreur de segmentation
```

**Comment by CDrummond** [comment]
Please run under gdb.
1. Rebuild with debug enbled - pass `-DCMAKE_BUILD_TYPE=Debug` to cmake
2. `> gdb cantata`
3. `gdb> run`
4. When it crashes, type `where`
5. Post results here

**Comment by edhelas** [comment]
Here we go 

```
(gdb) run
Starting program: /home/edhelas/Repositories/cantata/build/cantata 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe70b8700 (LWP 26440)]
qt5ct: using qt5ct plugin
[New Thread 0x7fffdbde0700 (LWP 26441)]

Thread 1 "cantata" received signal SIGSEGV, Segmentation fault.
0x00007ffff46b2e01 in QObject::property(char const*) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

**Comment by CDrummond** [comment]
You forgot to type `where` - this gives more info

**Comment by edhelas** [comment]
Okay :)

```
(gdb) where
#0  0x00007ffff46b2e01 in QObject::property(char const*) const ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00005555558114e3 in MainWindow::controlView(bool) (this=0x7fffffffd970, forceUpdate=false)
    at /home/edhelas/Repositories/cantata/gui/mainwindow.cpp:2619
#2  0x0000555555805ccb in MainWindow::resizeEvent(QResizeEvent*) (this=0x7fffffffd970, event=0x7fffffffd530) at /home/edhelas/Repositories/cantata/gui/mainwindow.cpp:1120
#3  0x00007ffff53e18f2 in QWidget::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff54f41fb in QMainWindow::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff53a263c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff53a9f04 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff4686258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff53d9dfb in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff53ddbd3 in QWidgetPrivate::show_helper() ()
---Type <return> to continue, or q <return> to quit---
   ts.so.5
#10 0x00007ffff53e08eb in QWidget::setVisible(bool) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00005555557f8df1 in MainWindow::MainWindow(QWidget*) (this=0x7fffffffd970, parent=0x0)
    at /home/edhelas/Repositories/cantata/gui/mainwindow.cpp:169
#12 0x0000555555874a50 in main(int, char**) (argc=1, argv=0x7fffffffe0b8)
    at /home/edhelas/Repositories/cantata/gui/main.cpp:412
```
