### ISSUE TITLE
cantata crashes during start

### ISSUE THREAD

**Issue by Samonitari** [CDrummond/cantata#793]
Just updated a lot a packages, including cantata a few days ago, and since then, cannot start cantata. 
Additional question: As I generated backtrace, I realized it still uses Qt4 libraries.
Is there some variable to start with Qt5 during start, or should I contact the packager?
Probably a dumb question, but I lack some expreience.
I'll happily provide more infos, just let me now what (and how to extract it).

Application: cantata (2.0.0)
KDE Platform Version: 4.14.15
Qt Version: 4.8.7
Operating System: Linux 4.4.0-1-default x86_64
Distribution: "openSUSE Tumbleweed (20160121) (x86_64)"
Plasma5 Workspace: 5.5.3-1.1

Installed debug symbols:
libqt4-debuginfo glibc-debuginfo libglib-2_0-0-debuginfo libkde4-debuginfo libqt4-x11-debuginfo cantata-debuginfo

```
Application: Cantata (cantata), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f9e06a7f940 (LWP 3105))]

Thread 2 (Thread 0x7f9defd61700 (LWP 3106)):
#0  0x00007f9e0139b24d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9dfead6264 in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x7f9de80013e0, timeout=<optimized out>, context=0x7f9de80009a0) at gmain.c:4135
#2  0x00007f9dfead6264 in g_main_context_iterate (context=context@entry=0x7f9de80009a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3835
#3  0x00007f9dfead636c in g_main_context_iteration (context=0x7f9de80009a0, may_block=may_block@entry=1) at gmain.c:3901
#4  0x00007f9e04a9629e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7f9de80008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:452
#5  0x00007f9e04a66411 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7f9defd60c80, flags=...) at kernel/qeventloop.cpp:149
#6  0x00007f9e04a66725 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7f9defd60c80, flags=...) at kernel/qeventloop.cpp:204
#7  0x00007f9e0495fa59 in QThread::exec() (this=this@entry=0x1a88700) at thread/qthread.cpp:538
#8  0x00007f9e0495fb75 in QThread::run() (this=this@entry=0x1a88700) at thread/qthread.cpp:605
#9  0x00000000007a8978 in Thread::run() (this=0x1a88700) at /usr/src/debug/cantata-2.0.0/support/thread.cpp:110
#10 0x00007f9e0496223c in QThreadPrivate::start(void*) (arg=0x1a88700) at thread/qthread_unix.cpp:352
#11 0x00007f9e02d614a4 in start_thread (arg=0x7f9defd61700) at pthread_create.c:334
#12 0x00007f9e013a3bdd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f9e06a7f940 (LWP 3105)):
[KCrash Handler]
#6  0x00007f9e0342ea50 in QSqlDatabase::QSqlDatabase(QSqlDatabase const&) () at /usr/lib64/libQtSql.so.4
#7  0x00000000005309d6 in LibraryDb::createTable(QString const&) (this=this@entry=0x20ba2a0, q=...) at /usr/src/debug/cantata-2.0.0/db/librarydb.cpp:1029
#8  0x00000000006db70c in OnlineDb::OnlineDb(QString const&, QObject*) (this=0x20ba2a0, serviceName=..., p=<optimized out>) at /usr/src/debug/cantata-2.0.0/db/onlinedb.cpp:36
#9  0x00000000006a781a in JamendoService::JamendoService(QObject*) (this=0x20ba220, p=0x202c880) at /usr/src/debug/cantata-2.0.0/online/jamendoservice.cpp:326
#10 0x00000000006a4ce2 in OnlineServicesPage::OnlineServicesPage(QWidget*) (this=0x202c880, p=<optimized out>) at /usr/src/debug/cantata-2.0.0/online/onlineservicespage.cpp:41
#11 0x0000000000578e5c in MainWindow::MainWindow(QWidget*) (this=0x1bbb500, parent=<optimized out>, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /usr/src/debug/cantata-2.0.0/gui/mainwindow.cpp:392
#12 0x00000000007a195e in Application::newInstance() (this=0x7ffcb22f21b0) at /usr/src/debug/cantata-2.0.0/gui/application_kde.cpp:82
#13 0x00007f9e02627c0b in KUniqueApplicationAdaptor::newInstance(QByteArray const&, QByteArray const&) (this=0x1aa9260, asn_id=..., args=...) at /usr/src/debug/kdelibs-4.14.15/kdeui/kernel/kuniqueapplication.cpp:442
#14 0x00007f9e02627c85 in KUniqueApplicationAdaptor::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=_o@entry=0x1aa9260, _id=_id@entry=0, _a=_a@entry=0x7ffcb22f1540, _c=QMetaObject::InvokeMetaMethod) at /usr/src/debug/kdelibs-4.14.15/build/kdeui/kuniqueapplication_p.moc:57
#15 0x00007f9e02627ed3 in KUniqueApplicationAdaptor::qt_metacall(QMetaObject::Call, int, void**) (_a=0x7ffcb22f1540, _id=0, _c=QMetaObject::InvokeMetaMethod, _o=0x1aa9260) at /usr/src/debug/kdelibs-4.14.15/build/kdeui/kuniqueapplication_p.moc:100
#16 0x00007f9e02627ed3 in KUniqueApplicationAdaptor::qt_metacall(QMetaObject::Call, int, void**) (this=0x1aa9260, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7ffcb22f1540) at /usr/src/debug/kdelibs-4.14.15/build/kdeui/kuniqueapplication_p.moc:101
#17 0x00007f9e031b8205 in QDBusConnectionPrivate::deliverCall(QObject*, int, QDBusMessage const&, QList<int> const&, int) (this=this@entry=0x18c1480, object=object@entry=0x1aa9260, msg=..., metaTypes=..., slotIdx=4) at qdbusintegrator.cpp:950
#18 0x00007f9e031b974b in QDBusConnectionPrivate::activateCall(QObject*, int, QDBusMessage const&) (this=this@entry=0x18c1480, object=0x1aa9260, flags=flags@entry=337, msg=...) at qdbusintegrator.cpp:856
#19 0x00007f9e031ba437 in QDBusConnectionPrivate::activateObject(QDBusConnectionPrivate::ObjectTreeNode&, QDBusMessage const&, int) (this=0x18c1480, node=..., msg=..., pathStartPos=<optimized out>) at qdbusintegrator.cpp:1427
#20 0x00007f9e031ba63b in QDBusActivateObjectEvent::placeMetaCall(QObject*) (this=0x1a8b370) at qdbusintegrator.cpp:1541
#21 0x00007f9e04a80ad1 in QObject::event(QEvent*) (this=this@entry=0x7ffcb22f21b0, e=e@entry=0x1a8b370) at kernel/qobject.cpp:1231
#22 0x00007f9e04a6be7c in QCoreApplication::event(QEvent*) (this=this@entry=0x7ffcb22f21b0, e=e@entry=0x1a8b370) at kernel/qcoreapplication.cpp:1767
#23 0x00007f9e03def2ef in QApplication::event(QEvent*) (this=0x7ffcb22f21b0, e=0x1a8b370) at kernel/qapplication.cpp:2544
#24 0x00007f9e03de9f1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x18e9b90, receiver=receiver@entry=0x7ffcb22f21b0, e=e@entry=0x1a8b370) at kernel/qapplication.cpp:4565
#25 0x00007f9e03df09ec in QApplication::notify(QObject*, QEvent*) (this=this@entry=0x7ffcb22f21b0, receiver=receiver@entry=0x7ffcb22f21b0, e=e@entry=0x1a8b370) at kernel/qapplication.cpp:4351
#26 0x00007f9e0262065a in KApplication::notify(QObject*, QEvent*) (this=0x7ffcb22f21b0, receiver=0x7ffcb22f21b0, event=0x1a8b370) at /usr/src/debug/kdelibs-4.14.15/kdeui/kernel/kapplication.cpp:311
#27 0x00007f9e04a67a4d in QCoreApplication::notifyInternal(QObject*, QEvent*) (this=0x7ffcb22f21b0, receiver=receiver@entry=0x7ffcb22f21b0, event=event@entry=0x1a8b370) at kernel/qcoreapplication.cpp:955
#28 0x00007f9e04a6ae7e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (event=0x1a8b370, receiver=0x7ffcb22f21b0) at kernel/qcoreapplication.h:231
#29 0x00007f9e04a6ae7e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x1891300) at kernel/qcoreapplication.cpp:1579
#30 0x00007f9e04a6b153 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1472
#31 0x00007f9e04a9610e in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) () at kernel/qcoreapplication.h:236
#32 0x00007f9e04a9610e in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x18de560) at kernel/qeventdispatcher_glib.cpp:300
#33 0x00007f9dfead6097 in g_main_context_dispatch (context=0x18d2f70) at gmain.c:3154
#34 0x00007f9dfead6097 in g_main_context_dispatch (context=context@entry=0x18d2f70) at gmain.c:3769
#35 0x00007f9dfead62c8 in g_main_context_iterate (context=context@entry=0x18d2f70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3840
#36 0x00007f9dfead636c in g_main_context_iteration (context=0x18d2f70, may_block=may_block@entry=1) at gmain.c:3901
#37 0x00007f9e04a9627e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x18d0f80, flags=...) at kernel/qeventdispatcher_glib.cpp:450
#38 0x00007f9e03e8d946 in QGuiEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#39 0x00007f9e04a66411 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffcb22f1da0, flags=...) at kernel/qeventloop.cpp:149
#40 0x00007f9e04a66725 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffcb22f1da0, flags=...) at kernel/qeventloop.cpp:204
#41 0x00007f9e04a6bf29 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1227
#42 0x00007f9e03de87dc in QApplication::exec() () at kernel/qapplication.cpp:3823
#43 0x000000000045283f in main(int, char**) (argc=<optimized out>, argv=0x7ffcb22f22f8) at /usr/src/debug/cantata-2.0.0/gui/main.cpp:377
```

**Comment by CDrummond** [comment]
KDE builds are Qt4 only. Cantata 2.x itself defaults to Qt5 builds.

Can't recreate this issue - looks like a problem with SQLite. Do you have this installed?

Anyway, please can you checkout master or the 2.0 branch. I've delayed the creation of the Jamendo and Magnatune DBs. If Cantata will now start, please then try showing the Jamendo page.

**Comment by Samonitari** [comment]
I have SQLite installed.
I'll definitely check the master branch today after I wake up :) (saturday, UTC).
By the way thanks for the awesome work of creating and maintaining th best Mpd client, for the reply, and for the patience till I get to test the master

**Comment by CDrummond** [comment]
When you checkout master - please compile the same as the 2.0.0 release. As I can't recreate the issue, its difficult to know if its fixed. Therefore, if you keep the compile as near to 2.0.0 as possible it'll give more more confidence in the fix.

**Comment by Samonitari** [comment]
I didn't need to checkout the latest.
As i was installing the build dependencies (which i couldn't finish, i got lost at some kde4 stuff), i tried again and it worked.
I rolled back the system (with snapper) to yesterday, and it turns out that only libqt4-sql-sqlite package was missing.
I'll report to the packager the missing dependency.
Thanks again!

**Comment by CDrummond** [comment]
Ah! That would explain it! Would be nice to make it a compile time dependency, just not sure how!

Well, at least it made me delay the DB initialisation. Before it created 2 empty DBs, even if you never entered the Jamendo/Magnatune sections...
